import { NextRequest, NextResponse } from 'next/server'

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || ''
const GROQ_API_KEY = process.env.GROQ_API_KEY || ''

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'

// Tools that use Gemini API (premium quality)
const GEMINI_TOOLS = ['resume', 'proposal', 'email', 'cover-letter']

// Tools that use Groq API (fast, lightweight)
const GROQ_TOOLS = ['bio', 'hashtag', 'youtube-title', 'caption']

async function generateWithGemini(prompt: string): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured')
  }

  const response = await fetch(
    `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        },
      }),
    }
  )

  if (!response.ok) {
    const error = await response.json()
    throw new Error(error.error?.message || 'Gemini API request failed')
  }

  const data = await response.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || ''

  if (!text) {
    throw new Error('No content generated by Gemini API')
  }

  return text
}

async function generateWithGroq(prompt: string): Promise<string> {
  if (!GROQ_API_KEY) {
    throw new Error('GROQ_API_KEY not configured')
  }

  const response = await fetch(GROQ_API_URL, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GROQ_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 1024,
    }),
  })

  if (!response.ok) {
    const error = await response.json()
    throw new Error(error.error?.message || 'Groq API request failed')
  }

  const data = await response.json()
  const text = data.choices?.[0]?.message?.content || ''

  if (!text) {
    throw new Error('No content generated by Groq API')
  }

  return text
}

function buildPrompt(toolType: string, formData: any): string {
  switch (toolType) {
    case 'resume': {
      const template = formData.selectedTemplate || 'modern'

      if (template === 'modern') {
        return `You are a professional resume writer. Generate a compelling, achievement-focused resume for a talented professional.

INPUT DATA:
Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

TASK: Enhance this resume content to be recruiter-ready and impressive.

CRITICAL INSTRUCTIONS:

1. PROFESSIONAL SUMMARY:
   - Write 2-3 punchy sentences that immediately establish credibility
   - Focus on unique value proposition and key strengths
   - Show personality while remaining professional
   - Avoid generic phrases like "hardworking" or "dedicated"

2. WORK EXPERIENCE - FORMAT & CONTENT:
   - Format EACH job entry exactly as: "Job Title at Company, City | MM/YYYY - MM/YYYY"
   - Include 3-4 achievement bullets per role (NOT generic duties)
   - Lead with strong action verbs: Led, Architected, Spearheaded, Transformed, Accelerated, Optimized, etc.
   - QUANTIFY all results when possible (%, numbers, $, time saved)
   - Use specific business metrics and outcomes
   - Show impact on team, company, and customers
   - Example format:
     "Senior Product Manager at TechCorp, San Francisco | 01/2020 - 06/2023
     - Spearheaded product redesign that increased user retention by 34% (250K users)
     - Led cross-functional team of 12 (engineering, design, marketing)
     - Accelerated feature delivery by 40% through Agile optimization"

3. EDUCATION - FORMAT:
   - Format as: "Degree Name, University Name | Graduation Year"
   - Include relevant honors, GPA (if 3.5+), or notable achievements
   - Example: "BS Computer Science, Stanford University | 2018 (Magna Cum Laude)"

4. SKILLS:
   - List only TRUE expertise areas (skills person actually has)
   - Prioritize by relevance to industry/role
   - Mix technical and soft skills
   - Keep to 10-15 most impactful skills

5. TONE & LANGUAGE:
   - Professional but not stuffy
   - Human-readable, NOT robotic
   - Confident without being arrogant
   - Specific and concrete (avoid vague language)
   - Recruiter-friendly and ATS-compatible

OUTPUT FORMAT:
- For each section (Summary, Experience, Education, Skills), provide ONLY the enhanced content
- NO markdown, NO bullet point symbols
- Use pipe symbol (|) to separate job title|company|dates
- Make content directly copy-paste ready

Return only the enhanced resume content. Do NOT include section headers.`
      } else if (template === 'minimal') {
        return `You are a professional resume writer specializing in elegant, minimal designs.

INPUT DATA:
Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

TASK: Create a refined, elegant resume that emphasizes quality over quantity.

CRITICAL INSTRUCTIONS:

1. TONE:
   - Sophisticated and refined
   - Confidently understated
   - Editorial quality writing
   - Show wisdom through restraint

2. PROFESSIONAL SUMMARY:
   - Single elegant paragraph (3 sentences max)
   - Establish unique positioning
   - Emphasize depth and impact
   - Avoid superlatives

3. WORK EXPERIENCE - FORMAT & CONTENT:
   - Format as: "Role at Company, City | From-To (dates)"
   - Include 2-3 key achievements per role
   - Use refined action verbs: Directed, Cultivated, Enhanced, Established, etc.
   - Include meaningful metrics but keep descriptions concise
   - Example:
     "Director of Strategy at Global Corp, New York | 2019-2023
     Enhanced operational efficiency through systematic process redesign
     Managed $50M budget across international teams"

4. EDUCATION:
   - Format: "Degree, University | Year"
   - Include honors only if prestigious
   - Example: "MBA, Harvard Business School | 2015"

5. SKILLS:
   - 8-12 carefully selected skills
   - Grouped by relevance
   - Present as elegant list

6. LANGUAGE RULES:
   - Use sophisticated vocabulary (but remain accessible)
   - Active voice, strong verbs
   - Minimize adjectives
   - Let accomplishments speak for themselves
   - Avoid buzzwords

OUTPUT FORMAT:
- Provide only the enhanced content (no headers)
- Use pipe symbol (|) to separate information
- Content should be refined and ready to use
- No markdown or symbols

Return only the polished resume content.`
      } else {
        // ATS-Optimized
        return `You are an ATS (Applicant Tracking System) optimization expert. Create a keyword-rich, machine-friendly resume.

INPUT DATA:
Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

TASK: Optimize this resume for ATS parsing while maintaining readability and impact.

CRITICAL INSTRUCTIONS:

1. PROFESSIONAL SUMMARY:
   - 3-4 sentences maximum
   - Include key industry terms and skills
   - Quantify experience when possible
   - Clear, direct language

2. WORK EXPERIENCE - FORMAT & CONTENT:
   - Format each role as: "Job Title at Company, City | MM/YYYY - MM/YYYY"
   - Include 3-5 achievement statements per role
   - Lead with relevant action verbs
   - Include quantifiable results
   - Use industry keywords naturally
   - Example format:
     "Senior Software Engineer at TechCorp, San Francisco | 01/2019 - 12/2022
     Engineered microservices architecture using Java and Kubernetes
     Increased system performance by 45% reducing API latency from 500ms to 275ms
     Led team of 4 engineers on mission-critical payment system"

3. EDUCATION:
   - Format: "Degree, Institution, Year"
   - Include relevant certifications
   - Include GPA if 3.5 or higher

4. SKILLS:
   - Organize by category if possible (Technical Skills, Leadership, etc.)
   - Use industry-standard terminology
   - Include both technical and soft skills
   - Use pipe separators: "Skill1 • Skill2 • Skill3"

5. ATS OPTIMIZATION:
   - Use standard section headers: PROFESSIONAL SUMMARY, PROFESSIONAL EXPERIENCE, EDUCATION, TECHNICAL SKILLS
   - No special characters or formatting
   - Plain text, easy to parse
   - Keywords appear naturally in context
   - Avoid graphics, tables, or special symbols

6. LANGUAGE:
   - Professional and direct
   - Industry-standard terminology
   - Measurable outcomes
   - Clear and scannable

OUTPUT FORMAT:
- Provide only the enhanced content
- Use pipe (|) to separate information
- Use bullet points or line breaks for clarity
- Machine-readable and human-readable
- No markdown symbols

Return only the ATS-optimized resume content.`
      }
    }

    case 'proposal':
      return `Generate a professional business proposal based on this information:

Project Name: ${formData.projectName}
Client Name: ${formData.clientName}
Project Description: ${formData.projectDescription}
Timeline: ${formData.timeline}
Budget: ${formData.budget}
Deliverables: ${formData.deliverables}
Your Company: ${formData.company}

Instructions:
- Create a comprehensive, professional proposal
- Include Executive Summary section
- Detail project scope and deliverables
- Include timeline/schedule
- Add pricing and payment terms
- Include terms and conditions
- Make it persuasive and professional
- Use clear formatting with sections`

    case 'email':
      return `Generate a professional business email based on this information:

Purpose: ${formData.purpose}
Recipient: ${formData.recipient}
Key Points: ${formData.keyPoints}
Tone: ${formData.tone || 'professional'}

Instructions:
- Create a complete, professional email
- Include an appropriate subject line
- Start with proper greeting
- Include relevant key points
- Add clear call-to-action
- Close professionally
- Keep it concise but complete
- Make it ready to send immediately`

    case 'cover-letter':
      return `Generate a professional cover letter based on this information:

Full Name: ${formData.fullName}
Position: ${formData.position}
Company: ${formData.company}
Your Experience: ${formData.experience}
Key Skills: ${formData.skills}
Why Interested: ${formData.whyInterested}

Instructions:
- Create a compelling, professional cover letter
- Include proper business letter formatting
- Highlight relevant experience and skills
- Show enthusiasm for the position
- Include specific achievements
- Close with call-to-action
- Make it personal and engaging`

    case 'bio':
      return `Generate a professional bio (max 160 characters) based on:

Name: ${formData.name}
Title: ${formData.title}
Industry: ${formData.industry}
Key Skills: ${formData.skills}
Tone: ${formData.tone || 'professional'}

Instructions:
- Keep it under 160 characters
- Make it professional and engaging
- Include main title/role
- Highlight unique value
- Use ${formData.tone} tone
- Suitable for LinkedIn/social media`

    case 'hashtag':
      return `Generate 15 relevant hashtags for:

Content Type: ${formData.contentType}
Topic: ${formData.topic}
Platform: ${formData.platform}

Instructions:
- Mix of popular and niche hashtags
- Relevant to the topic
- Platform-appropriate
- Format as #hashtag space-separated
- Avoid banned/controversial hashtags`

    case 'youtube-title':
      return `Generate 5 engaging YouTube video titles based on:

Topic: ${formData.topic}
Keywords: ${formData.keywords}
Target Audience: ${formData.targetAudience}

Instructions:
- Make titles clickable and engaging
- Include relevant keywords
- Keep under 60 characters
- Avoid clickbait, stay professional
- Appeal to target audience
- Number each title (1-5)`

    case 'caption':
      return `Generate a short, engaging social media caption (max 300 characters) based on:

Content Type: ${formData.contentType}
Topic: ${formData.topic}
Platform: ${formData.platform}
Tone: ${formData.tone || 'engaging'}

Instructions:
- Keep under 300 characters
- Make it engaging and shareable
- Include relevant emojis if appropriate
- Use ${formData.tone} tone
- Platform-specific formatting`

    default:
      throw new Error('Unknown tool type')
  }
}

export async function POST(request: NextRequest) {
  try {
    const { toolType, formData } = await request.json()

    // Validate input
    if (!toolType || !formData) {
      return NextResponse.json(
        { error: 'Missing toolType or formData' },
        { status: 400 }
      )
    }

    // Build prompt
    const prompt = buildPrompt(toolType, formData)

    // Choose API based on tool type
    let generatedText: string

    if (GEMINI_TOOLS.includes(toolType)) {
      try {
        generatedText = await generateWithGemini(prompt)
      } catch (error) {
        // Fallback to Groq if Gemini fails
        if (GROQ_API_KEY) {
          generatedText = await generateWithGroq(prompt)
        } else {
          throw error
        }
      }
    } else if (GROQ_TOOLS.includes(toolType)) {
      try {
        generatedText = await generateWithGroq(prompt)
      } catch (error) {
        // Fallback to Gemini if Groq fails
        if (GEMINI_API_KEY) {
          generatedText = await generateWithGemini(prompt)
        } else {
          throw error
        }
      }
    } else {
      return NextResponse.json(
        { error: 'Unknown tool type' },
        { status: 400 }
      )
    }

    return NextResponse.json({
      success: true,
      result: generatedText,
    })
  } catch (error) {
    console.error('AI generation error:', error)

    const errorMessage = error instanceof Error ? error.message : 'Failed to generate content'

    // Provide helpful error messages
    if (errorMessage.includes('API key')) {
      return NextResponse.json(
        { error: 'AI API not configured. Please contact support.' },
        { status: 500 }
      )
    }

    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    )
  }
}
