import { NextRequest, NextResponse } from 'next/server'

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || ''
const GROQ_API_KEY = process.env.GROQ_API_KEY || ''

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'
const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'

// Tools that use Gemini API (premium quality)
const GEMINI_TOOLS = ['resume', 'proposal', 'email', 'cover-letter']

// Tools that use Groq API (fast, lightweight)
const GROQ_TOOLS = ['bio', 'hashtag', 'youtube-title', 'caption']

async function generateWithGemini(prompt: string): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY not configured')
  }

  const response = await fetch(
    `${GEMINI_API_URL}?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        },
      }),
    }
  )

  if (!response.ok) {
    const error = await response.json()
    throw new Error(error.error?.message || 'Gemini API request failed')
  }

  const data = await response.json()
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || ''

  if (!text) {
    throw new Error('No content generated by Gemini API')
  }

  return text
}

async function generateWithGroq(prompt: string): Promise<string> {
  if (!GROQ_API_KEY) {
    throw new Error('GROQ_API_KEY not configured')
  }

  const response = await fetch(GROQ_API_URL, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GROQ_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_tokens: 1024,
    }),
  })

  if (!response.ok) {
    const error = await response.json()
    throw new Error(error.error?.message || 'Groq API request failed')
  }

  const data = await response.json()
  const text = data.choices?.[0]?.message?.content || ''

  if (!text) {
    throw new Error('No content generated by Groq API')
  }

  return text
}

function buildPrompt(toolType: string, formData: any): string {
  switch (toolType) {
    case 'resume': {
      const template = formData.selectedTemplate || 'modern'

      if (template === 'modern') {
        return `Generate a professional, achievement-focused resume based on this information:

Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

Instructions for MODERN PROFESSIONAL template:
- Create achievement-focused bullet points
- Use strong action verbs (Led, Designed, Managed, Increased, Improved, etc.)
- Quantify results where possible (e.g., "Increased sales by 25%")
- Keep each bullet point to 1-2 lines
- Include dates for all positions (format: MM/YYYY - MM/YYYY)
- Format each section clearly
- Make accomplishments prominent
- Professional tone, modern language
- ATS-friendly formatting

Return ONLY the enhanced content for each section, without markdown symbols.`
      } else if (template === 'minimal') {
        return `Generate a concise, elegantly-worded resume based on this information:

Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

Instructions for MINIMAL ELEGANT template:
- Use elegant, sophisticated language
- Focus on key accomplishments
- Keep descriptions concise (1 line per item)
- Include dates in parentheses format
- Emphasize quality over quantity
- Professional, timeless tone
- Minimize adjectives, use nouns and verbs
- Clean, refined presentation

Return ONLY the enhanced content for each section.`
      } else {
        // ATS-Optimized
        return `Generate a plain-text, ATS-optimized resume based on this information:

Full Name: ${formData.fullName}
Email: ${formData.email}
Phone: ${formData.phone}
Professional Summary: ${formData.summary || 'Not provided'}
Work Experience: ${formData.experience || 'Not provided'}
Education: ${formData.education || 'Not provided'}
Skills: ${formData.skills || 'Not provided'}

Instructions for ATS-OPTIMIZED template:
- Use simple, clear language without special characters
- Include relevant keywords naturally
- Use standard section names (Professional Summary, Experience, Education, Skills)
- Keep formatting plain and simple
- One item per line
- Include dates in standard format (MM/YYYY)
- Avoid graphics, symbols, and special formatting
- Focus on content that ATS systems can parse
- Professional, straightforward tone

Return ONLY the plain-text content without any markdown or special formatting.`
      }
    }

    case 'proposal':
      return `Generate a professional business proposal based on this information:

Project Name: ${formData.projectName}
Client Name: ${formData.clientName}
Project Description: ${formData.projectDescription}
Timeline: ${formData.timeline}
Budget: ${formData.budget}
Deliverables: ${formData.deliverables}
Your Company: ${formData.company}

Instructions:
- Create a comprehensive, professional proposal
- Include Executive Summary section
- Detail project scope and deliverables
- Include timeline/schedule
- Add pricing and payment terms
- Include terms and conditions
- Make it persuasive and professional
- Use clear formatting with sections`

    case 'email':
      return `Generate a professional business email based on this information:

Purpose: ${formData.purpose}
Recipient: ${formData.recipient}
Key Points: ${formData.keyPoints}
Tone: ${formData.tone || 'professional'}

Instructions:
- Create a complete, professional email
- Include an appropriate subject line
- Start with proper greeting
- Include relevant key points
- Add clear call-to-action
- Close professionally
- Keep it concise but complete
- Make it ready to send immediately`

    case 'cover-letter':
      return `Generate a professional cover letter based on this information:

Full Name: ${formData.fullName}
Position: ${formData.position}
Company: ${formData.company}
Your Experience: ${formData.experience}
Key Skills: ${formData.skills}
Why Interested: ${formData.whyInterested}

Instructions:
- Create a compelling, professional cover letter
- Include proper business letter formatting
- Highlight relevant experience and skills
- Show enthusiasm for the position
- Include specific achievements
- Close with call-to-action
- Make it personal and engaging`

    case 'bio':
      return `Generate a professional bio (max 160 characters) based on:

Name: ${formData.name}
Title: ${formData.title}
Industry: ${formData.industry}
Key Skills: ${formData.skills}
Tone: ${formData.tone || 'professional'}

Instructions:
- Keep it under 160 characters
- Make it professional and engaging
- Include main title/role
- Highlight unique value
- Use ${formData.tone} tone
- Suitable for LinkedIn/social media`

    case 'hashtag':
      return `Generate 15 relevant hashtags for:

Content Type: ${formData.contentType}
Topic: ${formData.topic}
Platform: ${formData.platform}

Instructions:
- Mix of popular and niche hashtags
- Relevant to the topic
- Platform-appropriate
- Format as #hashtag space-separated
- Avoid banned/controversial hashtags`

    case 'youtube-title':
      return `Generate 5 engaging YouTube video titles based on:

Topic: ${formData.topic}
Keywords: ${formData.keywords}
Target Audience: ${formData.targetAudience}

Instructions:
- Make titles clickable and engaging
- Include relevant keywords
- Keep under 60 characters
- Avoid clickbait, stay professional
- Appeal to target audience
- Number each title (1-5)`

    case 'caption':
      return `Generate a short, engaging social media caption (max 300 characters) based on:

Content Type: ${formData.contentType}
Topic: ${formData.topic}
Platform: ${formData.platform}
Tone: ${formData.tone || 'engaging'}

Instructions:
- Keep under 300 characters
- Make it engaging and shareable
- Include relevant emojis if appropriate
- Use ${formData.tone} tone
- Platform-specific formatting`

    default:
      throw new Error('Unknown tool type')
  }
}

export async function POST(request: NextRequest) {
  try {
    const { toolType, formData } = await request.json()

    // Validate input
    if (!toolType || !formData) {
      return NextResponse.json(
        { error: 'Missing toolType or formData' },
        { status: 400 }
      )
    }

    // Build prompt
    const prompt = buildPrompt(toolType, formData)

    // Choose API based on tool type
    let generatedText: string

    if (GEMINI_TOOLS.includes(toolType)) {
      try {
        generatedText = await generateWithGemini(prompt)
      } catch (error) {
        // Fallback to Groq if Gemini fails
        if (GROQ_API_KEY) {
          generatedText = await generateWithGroq(prompt)
        } else {
          throw error
        }
      }
    } else if (GROQ_TOOLS.includes(toolType)) {
      try {
        generatedText = await generateWithGroq(prompt)
      } catch (error) {
        // Fallback to Gemini if Groq fails
        if (GEMINI_API_KEY) {
          generatedText = await generateWithGemini(prompt)
        } else {
          throw error
        }
      }
    } else {
      return NextResponse.json(
        { error: 'Unknown tool type' },
        { status: 400 }
      )
    }

    return NextResponse.json({
      success: true,
      result: generatedText,
    })
  } catch (error) {
    console.error('AI generation error:', error)

    const errorMessage = error instanceof Error ? error.message : 'Failed to generate content'

    // Provide helpful error messages
    if (errorMessage.includes('API key')) {
      return NextResponse.json(
        { error: 'AI API not configured. Please contact support.' },
        { status: 500 }
      )
    }

    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    )
  }
}
