export const dynamic = 'force-dynamic'

import { Metadata } from 'next'
import { ProposalGeneratorForm } from '@/components/ai-tools/ProposalGeneratorForm'

export const metadata: Metadata = {
  title: 'AI Proposal Generator - MicroTools',
  description: 'Generate professional business proposals instantly with AI. Create winning proposals for clients and projects.',
  keywords: 'proposal generator, business proposal, proposal template, proposal writer',
  openGraph: {
    title: 'AI Proposal Generator - MicroTools',
    description: 'Generate professional business proposals instantly with AI',
    url: 'https://www.microtoolshub.org/ai-tools/proposal-generator',
    type: 'website',
  },
}

export default function ProposalGeneratorPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-12">
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-3">AI Proposal Generator</h1>
        <p className="text-lg text-muted-foreground">
          Create professional business proposals in minutes. Win more clients with compelling, well-structured proposals generated by AI.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-6 mb-12">
        <div className="p-4 bg-primary/10 rounded-lg border border-primary/20">
          <h3 className="font-semibold mb-2">💼 Professional</h3>
          <p className="text-sm text-muted-foreground">Business-ready proposals</p>
        </div>
        <div className="p-4 bg-primary/10 rounded-lg border border-primary/20">
          <h3 className="font-semibold mb-2">⚡ Quick</h3>
          <p className="text-sm text-muted-foreground">Generated in seconds</p>
        </div>
        <div className="p-4 bg-primary/10 rounded-lg border border-primary/20">
          <h3 className="font-semibold mb-2">✅ Persuasive</h3>
          <p className="text-sm text-muted-foreground">Designed to win clients</p>
        </div>
      </div>

      <ProposalGeneratorForm />

      <div className="mt-12 space-y-6">
        <section>
          <h2 className="text-2xl font-bold mb-3">What's Included</h2>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground">
            <li>Executive Summary</li>
            <li>Project Scope & Deliverables</li>
            <li>Timeline & Milestones</li>
            <li>Pricing & Payment Terms</li>
            <li>Terms & Conditions</li>
            <li>Professional formatting</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">How to Use</h2>
          <ol className="list-decimal list-inside space-y-2 text-muted-foreground">
            <li>Enter your project details and client information</li>
            <li>Click "Generate Proposal" and wait for AI to format it</li>
            <li>Review the complete proposal in the preview</li>
            <li>Copy and customize in Word, Google Docs, or PDF</li>
            <li>Send to your client</li>
          </ol>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">Pro Tips</h2>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground">
            <li>Be specific about deliverables and timeline</li>
            <li>Include realistic budget estimates</li>
            <li>Personalize with client name and context</li>
            <li>Highlight your company's unique value</li>
            <li>Customize the generated proposal before sending</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3">FAQ</h2>
          <div className="space-y-4 text-muted-foreground">
            <div>
              <h3 className="font-semibold mb-1">Can I customize the proposal?</h3>
              <p>Yes! Copy the generated proposal to Word, Google Docs, or any editor for customization.</p>
            </div>
            <div>
              <h3 className="font-semibold mb-1">Is my data saved?</h3>
              <p>No. Proposals are generated in real-time and not stored on our servers.</p>
            </div>
            <div>
              <h3 className="font-semibold mb-1">What format is the proposal in?</h3>
              <p>Generated in professional markdown format that can be copied to any document editor.</p>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}
