/**
 * Google AdSense Configuration
 * Auto ads + Manual ad placements
 */

export const ADSENSE_CONFIG = {
  // Replace with your AdSense Publisher ID
  // Format: pub-xxxxxxxxxxxxxxxx
  publisherId: process.env.NEXT_PUBLIC_ADSENSE_ID || '',

  // Enable auto ads (Google automatically places ads)
  autoAdsEnabled: true,

  // Target audience configuration
  targetAudience: {
    health: {
      keywords: ['health', 'fitness', 'wellness', 'diet', 'exercise'],
      interests: ['health-fitness', 'medical'],
    },
    finance: {
      keywords: ['finance', 'investment', 'money', 'savings', 'retirement'],
      interests: ['finance', 'investing', 'banking'],
    },
    seo: {
      keywords: ['seo', 'marketing', 'content', 'keywords', 'optimization'],
      interests: ['business-finance', 'web-design'],
    },
    developer: {
      keywords: ['coding', 'programming', 'development', 'web', 'software'],
      interests: ['technology', 'computers'],
    },
    converter: {
      keywords: ['converter', 'tools', 'calculation', 'units'],
      interests: ['technology', 'productivity-tools'],
    },
  },

  // Ad unit configurations
  adUnits: {
    // Homepage banner ads
    homepageBanner: {
      slotId: '1234567890', // Will be auto-generated by AdSense
      type: 'display',
      size: 'auto',
      responsive: true,
    },
    // Homepage sidebar ad
    homepageSidebar: {
      slotId: '1234567891',
      type: 'display',
      size: [300, 250],
      responsive: true,
    },
    // Tool page above results
    toolPageTop: {
      slotId: '1234567892',
      type: 'display',
      size: 'auto',
      responsive: true,
    },
    // Tool page below results
    toolPageBottom: {
      slotId: '1234567893',
      type: 'display',
      size: [728, 90],
      responsive: true,
    },
    // Blog page ads
    blogHeader: {
      slotId: '1234567894',
      type: 'display',
      size: 'auto',
      responsive: true,
    },
    blogSidebar: {
      slotId: '1234567895',
      type: 'display',
      size: [300, 600],
      responsive: true,
    },
  },

  // Content targeting
  contentTargeting: {
    excludedCategories: [
      'alcohol',
      'tobacco',
      'gambling',
      'violence',
      'sexual-content',
    ],
    restrictedPlacement: false,
  },

  // Analytics tracking
  trackAdClicks: true,
  trackAdImpressions: true,
}

export function isAdSenseConfigured(): boolean {
  return !!ADSENSE_CONFIG.publisherId
}
