export {
  GA_MEASUREMENT_ID,
  pageView,
  trackEvent,
  trackToolUsage,
  trackToolCalculation,
  trackClick,
  trackFormSubmission,
  trackNavigation,
  trackSearch,
  trackBlogView,
  trackScrollDepth,
  trackExternalLinkClick,
  trackError,
  trackEngagement,
} from '@/lib/ga4'
